name: Deploy to Production

on:
  push:
    branches:
      - main  # замените на имя вашей ветки, если это не main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Другие шаги, такие как сборка проекта или тестирование, если это необходимо

      - name: Deploy to server
        uses: appleboy/ssh-action@master  # Это просто пример, возможно, вам понадобится другой action или настройка
        with:
          host: ${{ secrets.HOST_BETNET_APP }}
          username: root
          password: ${{ secrets.PASS_BETNET_APP }}
          script: |
            cd /var/www/testcicd
            git pull
